services:
  # Backend Django REST API
  - type: web
    name: appli-imob-backend
    runtime: python
    rootDir: backend
    buildCommand: "./build.sh"
    startCommand: "gunicorn config.wsgi:application --bind 0.0.0.0:$PORT --workers 2"
    plan: free
    region: frankfurt # ou oregon / ohio
    envVars:
      - key: DJANGO_ENV
        value: production
      - key: DEBUG
        value: "False"
      - key: PYTHON_VERSION
        value: 3.12.0
      - key: SECRET_KEY
        generateValue: true
      - key: ALLOWED_HOSTS
        value: ".onrender.com,localhost,127.0.0.1"
      - key: CSRF_TRUSTED_ORIGINS
        value: "https://*.onrender.com,https://*.vercel.app"
      - key: CELERY_TASK_ALWAYS_EAGER
        value: "True"
      - key: SEED_DEMO_DATA
        value: "True"
      - key: DATABASE_URL
        sync: false
      - key: CORS_ALLOWED_ORIGINS
        sync: false
