# Generated by Django 5.1.15 on 2026-08-21 12:21

import django.core.validators
import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('properties', '0001_initial'),
        ('tenants', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Lease',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Identifiant unique universel (UUIDv4)', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Dernière modification')),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text="Indique si l'enregistrement est actif ou archivé (soft delete)", verbose_name='Actif')),
                ('start_date', models.DateField(verbose_name="Date d'entrée / Prise d'effet")),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='Date de fin de bail (si déterminée)')),
                ('rent_amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Loyer mensuel hors charges')),
                ('charges_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='Provisions de charges mensuelles')),
                ('deposit_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='Montant du dépôt de garantie (Caution)')),
                ('payment_day_of_month', models.PositiveSmallIntegerField(default=5, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(31)], verbose_name="Jour d'exigibilité du loyer dans le mois (1 à 31)")),
                ('payment_frequency', models.CharField(choices=[('MONTHLY', 'Mensuelle'), ('QUARTERLY', 'Trimestrielle'), ('SEMI_ANNUAL', 'Semestrielle'), ('ANNUAL', 'Annuelle')], default='MONTHLY', max_length=20, verbose_name='Périodicité des paiements')),
                ('status', models.CharField(choices=[('DRAFT', 'Brouillon'), ('ACTIVE', 'Actif / En cours'), ('TERMINATED', 'Résilié'), ('EXPIRED', 'Expiré'), ('CANCELLED', 'Annulé')], db_index=True, default='ACTIVE', max_length=20, verbose_name='Statut du contrat')),
                ('terms_and_conditions', models.TextField(blank=True, verbose_name='Clauses particulières et conditions')),
                ('owner', models.ForeignKey(help_text='Propriétaire gestionnaire de cette ressource', on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_owned', to=settings.AUTH_USER_MODEL, verbose_name='Propriétaire')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='leases', to='tenants.tenant', verbose_name='Locataire titulaire')),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='leases', to='properties.unit', verbose_name='Logement concerné')),
            ],
            options={
                'verbose_name': 'Contrat de bail',
                'verbose_name_plural': 'Contrats de bail',
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Deposit',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Identifiant unique universel (UUIDv4)', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Dernière modification')),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text="Indique si l'enregistrement est actif ou archivé (soft delete)", verbose_name='Actif')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Montant de la caution exigé')),
                ('received_date', models.DateField(blank=True, null=True, verbose_name="Date d'encaissement")),
                ('status', models.CharField(choices=[('PENDING', 'En attente d’encaissement'), ('PAID', 'Encaissée / Déposée'), ('REFUNDED', 'Restituée intégralement'), ('PARTIALLY_REFUNDED', 'Restituée partiellement'), ('RETAINED', 'Retenue pour dégradations / impayés')], db_index=True, default='PENDING', max_length=30, verbose_name='Statut de la caution')),
                ('refunded_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='Montant restitué au locataire')),
                ('refunded_date', models.DateField(blank=True, null=True, verbose_name='Date de restitution')),
                ('deduction_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='Montant retenu (dégradations/charges)')),
                ('deduction_reason', models.TextField(blank=True, verbose_name='Motif des retenues sur caution')),
                ('lease', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='deposit', to='leases.lease', verbose_name='Contrat de bail')),
            ],
            options={
                'verbose_name': 'Caution / Dépôt de garantie',
                'verbose_name_plural': 'Cautions & Dépôts de garantie',
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
    ]
