# Generated by Django 5.1.15 on 2026-08-21 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leases', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lease',
            options={'ordering': ['-start_date'], 'verbose_name': 'Contrat de bail', 'verbose_name_plural': 'Contrats de bail'},
        ),
        migrations.AddField(
            model_name='deposit',
            name='payment_method',
            field=models.CharField(blank=True, max_length=50, verbose_name='Moyen de règlement'),
        ),
        migrations.AddField(
            model_name='deposit',
            name='receipt_reference',
            field=models.CharField(blank=True, max_length=100, verbose_name='Référence du reçu'),
        ),
        migrations.AddField(
            model_name='lease',
            name='lease_number',
            field=models.CharField(blank=True, max_length=50, verbose_name='Numéro de contrat'),
        ),
        migrations.AddField(
            model_name='lease',
            name='termination_date',
            field=models.DateField(blank=True, null=True, verbose_name='Date de résiliation effective'),
        ),
        migrations.AddField(
            model_name='lease',
            name='termination_reason',
            field=models.TextField(blank=True, verbose_name='Motif de résiliation'),
        ),
        migrations.AlterField(
            model_name='lease',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Brouillon'), ('ACTIVE', 'Actif / En cours'), ('TERMINATED', 'Résilié'), ('EXPIRED', 'Expiré'), ('CANCELLED', 'Annulé')], db_index=True, default='DRAFT', max_length=20, verbose_name='Statut du contrat'),
        ),
    ]
