# Generated by Django 5.1.15 on 2026-08-21 12:21

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('properties', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Identifiant unique universel (UUIDv4)', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Dernière modification')),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text="Indique si l'enregistrement est actif ou archivé (soft delete)", verbose_name='Actif')),
                ('category', models.CharField(choices=[('REPAIRS', 'Travaux & Réparations'), ('MAINTENANCE', 'Entretien courant'), ('INSURANCE', 'Assurance PNO / Immeuble'), ('UTILITIES', 'Eau & Électricité parties communes'), ('MANAGEMENT', 'Frais de gestion / Syndic'), ('SECURITY', 'Gardiennage & Sécurité'), ('MORTGAGE', 'Intérêts d’emprunt'), ('OTHER', 'Autres charges')], default='MAINTENANCE', max_length=30, verbose_name='Catégorie de dépense')),
                ('title', models.CharField(max_length=255, verbose_name='Intitulé de la dépense')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Montant TTC (Decimal)')),
                ('expense_date', models.DateField(db_index=True, verbose_name='Date de paiement')),
                ('paid_to', models.CharField(blank=True, max_length=200, verbose_name='Bénéficiaire / Fournisseur payé')),
                ('receipt_file', models.FileField(blank=True, null=True, upload_to='expenses_receipts/', verbose_name="Justificatif / Facture d'achat")),
                ('is_deductible', models.BooleanField(default=True, verbose_name='Déductible fiscalement')),
                ('notes', models.TextField(blank=True, verbose_name='Notes et détails')),
                ('owner', models.ForeignKey(help_text='Propriétaire gestionnaire de cette ressource', on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_owned', to=settings.AUTH_USER_MODEL, verbose_name='Propriétaire')),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expenses', to='properties.property', verbose_name='Immeuble concerné')),
                ('unit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='expenses', to='properties.unit', verbose_name='Logement spécifique (facultatif)')),
            ],
            options={
                'verbose_name': 'Dépense',
                'verbose_name_plural': 'Dépenses',
                'ordering': ['-expense_date'],
                'abstract': False,
            },
        ),
    ]
