# Generated by Django 5.1.15 on 2026-08-21 13:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0001_initial'),
        ('maintenance', '0002_alter_maintenancerequest_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='expense',
            options={'ordering': ['-expense_date', '-created_at'], 'verbose_name': 'Dépense', 'verbose_name_plural': 'Dépenses'},
        ),
        migrations.AddField(
            model_name='expense',
            name='expense_number',
            field=models.CharField(blank=True, db_index=True, max_length=50, null=True, unique=True, verbose_name='Numéro de dépense'),
        ),
        migrations.AddField(
            model_name='expense',
            name='supplier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='expenses', to='maintenance.supplier', verbose_name='Fournisseur / Prestataire payé'),
        ),
        migrations.AlterField(
            model_name='expense',
            name='category',
            field=models.CharField(choices=[('REPAIRS', 'Travaux & Réparations'), ('MAINTENANCE', 'Entretien courant'), ('INSURANCE', 'Assurance PNO / Immeuble'), ('UTILITIES', 'Eau & Électricité parties communes'), ('MANAGEMENT', 'Frais de gestion / Syndic'), ('SECURITY', 'Gardiennage & Sécurité'), ('MORTGAGE', 'Intérêts d’emprunt'), ('OTHER', 'Autres charges')], db_index=True, default='MAINTENANCE', max_length=30, verbose_name='Catégorie de dépense'),
        ),
        migrations.AlterField(
            model_name='expense',
            name='is_deductible',
            field=models.BooleanField(db_index=True, default=True, verbose_name='Déductible fiscalement'),
        ),
    ]
