# Generated by Django 5.1.15 on 2026-08-21 12:21

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Identifiant unique universel (UUIDv4)', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Dernière modification')),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text="Indique si l'enregistrement est actif ou archivé (soft delete)", verbose_name='Actif')),
                ('action', models.CharField(choices=[('CREATE', 'Création'), ('UPDATE', 'Modification'), ('DELETE', 'Suppression'), ('CANCEL', 'Annulation'), ('ALLOCATE', 'Allocation de paiement'), ('LOGIN', 'Connexion'), ('LOGOUT', 'Déconnexion')], db_index=True, max_length=30, verbose_name='Action')),
                ('resource_type', models.CharField(db_index=True, max_length=100, verbose_name="Type d'entité")),
                ('resource_id', models.CharField(db_index=True, max_length=100, verbose_name='Identifiant entité')),
                ('changes', models.JSONField(blank=True, default=dict, verbose_name='Détails des modifications (avant/après)')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='Adresse IP')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to=settings.AUTH_USER_MODEL, verbose_name="Auteur de l'action")),
            ],
            options={
                'verbose_name': "Trace d'audit",
                'verbose_name_plural': "Traces d'audit",
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
    ]
