# Generated by Django 5.1.15 on 2026-08-21 12:21

import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('leases', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RentInvoice',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Identifiant unique universel (UUIDv4)', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Dernière modification')),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text="Indique si l'enregistrement est actif ou archivé (soft delete)", verbose_name='Actif')),
                ('invoice_number', models.CharField(db_index=True, max_length=50, unique=True, verbose_name="Numéro de facture / Avis d'échéance")),
                ('period_start', models.DateField(verbose_name='Début de période')),
                ('period_end', models.DateField(verbose_name='Fin de période')),
                ('due_date', models.DateField(db_index=True, verbose_name="Date d'exigibilité / Échéance")),
                ('rent_amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Montant loyer net')),
                ('charges_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='Montant charges')),
                ('total_expected', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Montant total attendu')),
                ('total_paid', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='Montant total perçu / alloué')),
                ('remaining_balance', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Solde restant dû')),
                ('status', models.CharField(choices=[('UNPAID', 'Impayé / Non réglé'), ('PARTIAL', 'Partiellement payé'), ('PAID', 'Payé intégralement'), ('OVERDUE', 'En retard d’échéance'), ('CANCELLED', 'Annulée')], db_index=True, default='UNPAID', max_length=20, verbose_name="Statut de l'échéance")),
                ('notes', models.TextField(blank=True, verbose_name='Remarques et annotations')),
                ('lease', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='invoices', to='leases.lease', verbose_name='Contrat de bail')),
                ('owner', models.ForeignKey(help_text='Propriétaire gestionnaire de cette ressource', on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_owned', to=settings.AUTH_USER_MODEL, verbose_name='Propriétaire')),
            ],
            options={
                'verbose_name': "Avis d'échéance / Facture de loyer",
                'verbose_name_plural': "Avis d'échéance & Factures de loyer",
                'ordering': ['-due_date'],
                'abstract': False,
            },
        ),
    ]
