# Generated by Django 5.1.15 on 2026-08-21 12:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='rentinvoice',
            options={'ordering': ['-due_date', '-created_at'], 'verbose_name': "Avis d'échéance / Facture de loyer", 'verbose_name_plural': "Avis d'échéance & Factures de loyer"},
        ),
    ]
