# Generated by Django 5.1.15 on 2026-08-21 12:21

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('properties', '0001_initial'),
        ('tenants', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Identifiant unique universel (UUIDv4)', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Dernière modification')),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text="Indique si l'enregistrement est actif ou archivé (soft delete)", verbose_name='Actif')),
                ('name', models.CharField(max_length=200, verbose_name="Nom de l'entreprise / artisan")),
                ('category', models.CharField(choices=[('PLUMBING', 'Plomberie & Sanitaire'), ('ELECTRICAL', 'Électricité & Domotique'), ('MASONRY', 'Maçonnerie & Gros œuvre'), ('PAINTING', 'Peinture & Finitions'), ('CLEANING', 'Nettoyage & Entretien'), ('HVAC', 'Climatisation & Chauffage'), ('SECURITY', 'Gardiennage & Sécurité'), ('OTHER', 'Autre')], default='PLUMBING', max_length=30, verbose_name="Corps d'état / Spécialité")),
                ('contact_name', models.CharField(blank=True, max_length=150, verbose_name='Interlocuteur principal')),
                ('phone_number', models.CharField(max_length=30, verbose_name='Téléphone')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('address', models.CharField(blank=True, max_length=255, verbose_name='Adresse')),
                ('tax_id', models.CharField(blank=True, max_length=50, verbose_name='Numéro SIRET / Registre de commerce')),
                ('notes', models.TextField(blank=True, verbose_name='Notes et tarifs indicatifs')),
                ('owner', models.ForeignKey(help_text='Propriétaire gestionnaire de cette ressource', on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_owned', to=settings.AUTH_USER_MODEL, verbose_name='Propriétaire')),
            ],
            options={
                'verbose_name': 'Fournisseur / Prestataire',
                'verbose_name_plural': 'Fournisseurs & Prestataires',
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='MaintenanceRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Identifiant unique universel (UUIDv4)', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Dernière modification')),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text="Indique si l'enregistrement est actif ou archivé (soft delete)", verbose_name='Actif')),
                ('title', models.CharField(max_length=255, verbose_name="Objet de l'intervention")),
                ('description', models.TextField(verbose_name='Description détaillée du problème')),
                ('priority', models.CharField(choices=[('LOW', 'Basse'), ('MEDIUM', 'Moyenne'), ('HIGH', 'Haute'), ('URGENT', 'Urgente / Critique')], db_index=True, default='MEDIUM', max_length=20, verbose_name="Degré d'urgence")),
                ('status', models.CharField(choices=[('REPORTED', 'Signalée'), ('ASSIGNED', 'Assignée au prestataire'), ('IN_PROGRESS', 'En cours d’intervention'), ('COMPLETED', 'Terminée et validée'), ('CANCELLED', 'Annulée')], db_index=True, default='REPORTED', max_length=20, verbose_name="État d'avancement")),
                ('estimated_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Devis estimatif')),
                ('actual_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Coût réel final')),
                ('reported_date', models.DateField(auto_now_add=True, verbose_name='Date de signalement')),
                ('completed_date', models.DateField(blank=True, null=True, verbose_name='Date de fin des travaux')),
                ('owner', models.ForeignKey(help_text='Propriétaire gestionnaire de cette ressource', on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_owned', to=settings.AUTH_USER_MODEL, verbose_name='Propriétaire')),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='maintenance_requests', to='properties.property', verbose_name='Immeuble concerné')),
                ('reported_by_tenant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='maintenance_requests', to='tenants.tenant', verbose_name='Locataire signalant')),
                ('unit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='maintenance_requests', to='properties.unit', verbose_name='Logement concerné (vide si parties communes)')),
                ('supplier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='interventions', to='maintenance.supplier', verbose_name='Prestataire assigné')),
            ],
            options={
                'verbose_name': 'Intervention de maintenance',
                'verbose_name_plural': 'Interventions de maintenance',
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
    ]
