# Generated by Django 5.1.15 on 2026-08-21 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='maintenancerequest',
            options={'ordering': ['-reported_date', '-created_at'], 'verbose_name': 'Intervention de maintenance', 'verbose_name_plural': 'Interventions de maintenance'},
        ),
        migrations.AlterModelOptions(
            name='supplier',
            options={'ordering': ['name'], 'verbose_name': 'Fournisseur / Prestataire', 'verbose_name_plural': 'Fournisseurs & Prestataires'},
        ),
        migrations.AddField(
            model_name='maintenancerequest',
            name='ticket_number',
            field=models.CharField(blank=True, db_index=True, max_length=50, null=True, unique=True, verbose_name='Numéro de ticket / Dossier'),
        ),
    ]
