# Generated by Django 5.1.15 on 2026-08-21 12:21

import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Identifiant unique universel (UUIDv4)', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Dernière modification')),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text="Indique si l'enregistrement est actif ou archivé (soft delete)", verbose_name='Actif')),
                ('name', models.CharField(max_length=255, verbose_name="Nom de l'immeuble / propriété")),
                ('code', models.CharField(blank=True, max_length=50, verbose_name='Code référence')),
                ('property_type', models.CharField(choices=[('BUILDING', 'Immeuble'), ('RESIDENCE', 'Résidence'), ('COMMERCIAL', 'Centre Commercial'), ('VILLA', 'Villa'), ('LAND', 'Terrain')], default='BUILDING', max_length=30, verbose_name='Type de bien')),
                ('address', models.CharField(max_length=255, verbose_name='Adresse')),
                ('city', models.CharField(max_length=100, verbose_name='Ville')),
                ('postal_code', models.CharField(blank=True, max_length=20, verbose_name='Code Postal')),
                ('country', models.CharField(default='France', max_length=100, verbose_name='Pays')),
                ('description', models.TextField(blank=True, verbose_name='Description détaillée')),
                ('purchase_price', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True, verbose_name="Prix d'acquisition")),
                ('estimated_value', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True, verbose_name='Valeur estimée actuelle')),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='properties/', verbose_name='Photo principale')),
                ('owner', models.ForeignKey(help_text='Propriétaire gestionnaire de cette ressource', on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_owned', to=settings.AUTH_USER_MODEL, verbose_name='Propriétaire')),
            ],
            options={
                'verbose_name': 'Immeuble / Propriété',
                'verbose_name_plural': 'Immeubles & Propriétés',
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Identifiant unique universel (UUIDv4)', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Dernière modification')),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text="Indique si l'enregistrement est actif ou archivé (soft delete)", verbose_name='Actif')),
                ('unit_number', models.CharField(max_length=50, verbose_name='Numéro de porte / Référence lot')),
                ('floor', models.CharField(blank=True, max_length=30, verbose_name='Étage')),
                ('unit_type', models.CharField(choices=[('STUDIO', 'Studio'), ('T1', 'Appartement T1'), ('T2', 'Appartement T2'), ('T3', 'Appartement T3'), ('T4', 'Appartement T4'), ('T5_PLUS', 'Appartement T5 ou plus'), ('VILLA', 'Villa'), ('COMMERCIAL', 'Local Commercial'), ('OFFICE', 'Bureau'), ('PARKING', 'Parking / Box')], default='T2', max_length=30, verbose_name='Type de logement')),
                ('surface_area_sqm', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Surface (m²)')),
                ('rooms_count', models.PositiveIntegerField(default=1, verbose_name='Nombre de pièces')),
                ('bathrooms_count', models.PositiveIntegerField(default=1, verbose_name="Nombre de salles d'eau")),
                ('base_rent_amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Loyer de base hors charges (FCFA / EUR)')),
                ('service_charges_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='Provisions sur charges')),
                ('status', models.CharField(choices=[('VACANT', 'Libre / Disponible'), ('OCCUPIED', 'Occupé'), ('MAINTENANCE', 'En Travaux / Rénovation'), ('RESERVED', 'Réservé')], db_index=True, default='VACANT', max_length=20, verbose_name='Statut du logement')),
                ('description', models.TextField(blank=True, verbose_name='Description du logement')),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='units', to='properties.property', verbose_name='Immeuble / Propriété')),
            ],
            options={
                'verbose_name': 'Logement / Lot',
                'verbose_name_plural': 'Logements & Lots',
                'ordering': ['-created_at'],
                'abstract': False,
                'unique_together': {('property', 'unit_number')},
            },
        ),
    ]
