# Generated by Django 5.1.15 on 2026-08-21 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='property',
            options={'ordering': ['name'], 'verbose_name': 'Immeuble / Propriété', 'verbose_name_plural': 'Immeubles & Propriétés'},
        ),
        migrations.AlterModelOptions(
            name='unit',
            options={'ordering': ['unit_number'], 'verbose_name': 'Logement / Lot', 'verbose_name_plural': 'Logements & Lots'},
        ),
        migrations.AddField(
            model_name='property',
            name='notes',
            field=models.TextField(blank=True, verbose_name='Notes internes'),
        ),
        migrations.AddField(
            model_name='unit',
            name='electricity_meter_number',
            field=models.CharField(blank=True, max_length=50, verbose_name='N° Compteur Électricité'),
        ),
        migrations.AddField(
            model_name='unit',
            name='water_meter_number',
            field=models.CharField(blank=True, max_length=50, verbose_name='N° Compteur Eau'),
        ),
        migrations.AlterField(
            model_name='property',
            name='country',
            field=models.CharField(default="Côte d'Ivoire", max_length=100, verbose_name='Pays'),
        ),
    ]
