# Generated by Django 5.1.15 on 2026-08-21 12:21

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('leases', '0001_initial'),
        ('properties', '0001_initial'),
        ('tenants', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Identifiant unique universel (UUIDv4)', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Dernière modification')),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text="Indique si l'enregistrement est actif ou archivé (soft delete)", verbose_name='Actif')),
                ('title', models.CharField(max_length=255, verbose_name='Titre du document')),
                ('document_type', models.CharField(choices=[('LEASE_CONTRACT', 'Contrat de bail'), ('ID_CARD', 'Pièce d’identité'), ('RENT_RECEIPT', 'Quittance de loyer'), ('INVOICE', 'Facture / Avis d’échéance'), ('TAX_NOTICE', 'Avis fiscal'), ('INSURANCE', 'Contrat d’assurance'), ('PROPERTY_DEED', 'Titre de propriété'), ('PHOTO', 'Photo / État des lieux'), ('OTHER', 'Autre document')], db_index=True, default='OTHER', max_length=30, verbose_name='Catégorie de document')),
                ('file', models.FileField(upload_to='documents/%Y/%m/', verbose_name='Fichier')),
                ('file_size_bytes', models.PositiveBigIntegerField(blank=True, null=True, verbose_name='Taille en octets')),
                ('mime_type', models.CharField(blank=True, max_length=100, verbose_name='Type MIME')),
                ('description', models.TextField(blank=True, verbose_name='Description / Commentaires')),
                ('lease', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documents', to='leases.lease', verbose_name='Bail rattaché')),
                ('owner', models.ForeignKey(help_text='Propriétaire gestionnaire de cette ressource', on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_owned', to=settings.AUTH_USER_MODEL, verbose_name='Propriétaire')),
                ('property', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documents', to='properties.property', verbose_name='Immeuble rattaché')),
                ('tenant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documents', to='tenants.tenant', verbose_name='Locataire rattaché')),
                ('unit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documents', to='properties.unit', verbose_name='Logement rattaché')),
            ],
            options={
                'verbose_name': 'Document',
                'verbose_name_plural': 'Documents & Fichiers',
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
    ]
