# Generated by Django 5.1.15 on 2026-08-21 12:21

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Tenant',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Identifiant unique universel (UUIDv4)', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Dernière modification')),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text="Indique si l'enregistrement est actif ou archivé (soft delete)", verbose_name='Actif')),
                ('first_name', models.CharField(max_length=100, verbose_name='Prénom')),
                ('last_name', models.CharField(max_length=100, verbose_name='Nom de famille')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Adresse Email')),
                ('phone_number', models.CharField(max_length=30, verbose_name='Numéro de téléphone principal')),
                ('secondary_phone', models.CharField(blank=True, max_length=30, verbose_name='Numéro de téléphone secondaire')),
                ('id_card_number', models.CharField(blank=True, max_length=50, verbose_name='Numéro CNI / Passeport')),
                ('profession', models.CharField(blank=True, max_length=150, verbose_name='Profession')),
                ('employer', models.CharField(blank=True, max_length=150, verbose_name='Employeur / Entreprise')),
                ('monthly_income', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Revenu mensuel net déclaré')),
                ('notes', models.TextField(blank=True, verbose_name='Remarques et antécédents')),
                ('owner', models.ForeignKey(help_text='Propriétaire gestionnaire de cette ressource', on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_owned', to=settings.AUTH_USER_MODEL, verbose_name='Propriétaire')),
            ],
            options={
                'verbose_name': 'Locataire',
                'verbose_name_plural': 'Locataires',
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='EmergencyContact',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Identifiant unique universel (UUIDv4)', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Dernière modification')),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text="Indique si l'enregistrement est actif ou archivé (soft delete)", verbose_name='Actif')),
                ('name', models.CharField(max_length=150, verbose_name='Nom complet du contact')),
                ('relationship', models.CharField(blank=True, max_length=100, verbose_name='Lien de parenté / Relation')),
                ('phone_number', models.CharField(max_length=30, verbose_name='Téléphone')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emergency_contacts', to='tenants.tenant', verbose_name='Locataire')),
            ],
            options={
                'verbose_name': "Contact d'urgence",
                'verbose_name_plural': "Contacts d'urgence",
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
    ]
