# Generated by Django 5.1.15 on 2026-08-21 12:42

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tenant',
            options={'ordering': ['last_name', 'first_name', 'company_name'], 'verbose_name': 'Locataire', 'verbose_name_plural': 'Locataires'},
        ),
        migrations.AddField(
            model_name='tenant',
            name='address',
            field=models.CharField(blank=True, max_length=255, verbose_name='Adresse de domiciliation'),
        ),
        migrations.AddField(
            model_name='tenant',
            name='city',
            field=models.CharField(default='Abidjan', max_length=100, verbose_name='Ville'),
        ),
        migrations.AddField(
            model_name='tenant',
            name='company_name',
            field=models.CharField(blank=True, max_length=200, verbose_name='Raison Sociale / Nom Entreprise'),
        ),
        migrations.AddField(
            model_name='tenant',
            name='country',
            field=models.CharField(default="Côte d'Ivoire", max_length=100, verbose_name='Pays'),
        ),
        migrations.AddField(
            model_name='tenant',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True, verbose_name='Date de naissance / Création'),
        ),
        migrations.AddField(
            model_name='tenant',
            name='id_card_type',
            field=models.CharField(choices=[('CNI', "Carte Nationale d'Identité"), ('PASSPORT', 'Passeport'), ('RESIDENCE_PERMIT', 'Titre de Séjour / Carte Consulaire'), ('RCCM', 'Registre du Commerce (RCCM)'), ('OTHER', 'Autre pièce officielle')], default='CNI', max_length=30, verbose_name="Type de pièce d'identité"),
        ),
        migrations.AddField(
            model_name='tenant',
            name='postal_code',
            field=models.CharField(blank=True, max_length=20, verbose_name='Code Postal'),
        ),
        migrations.AddField(
            model_name='tenant',
            name='tax_id',
            field=models.CharField(blank=True, max_length=50, verbose_name='Compte Contribuable / NIF / Numéro Fiscal'),
        ),
        migrations.AddField(
            model_name='tenant',
            name='tenant_type',
            field=models.CharField(choices=[('INDIVIDUAL', 'Particulier'), ('COMPANY', 'Entreprise / Personne Morale')], default='INDIVIDUAL', max_length=20, verbose_name='Type de locataire'),
        ),
        migrations.AlterField(
            model_name='tenant',
            name='first_name',
            field=models.CharField(blank=True, max_length=100, verbose_name='Prénom'),
        ),
        migrations.AlterField(
            model_name='tenant',
            name='id_card_number',
            field=models.CharField(blank=True, max_length=50, verbose_name='Numéro de pièce / RCCM'),
        ),
        migrations.AlterField(
            model_name='tenant',
            name='last_name',
            field=models.CharField(blank=True, max_length=100, verbose_name='Nom de famille'),
        ),
        migrations.AlterField(
            model_name='tenant',
            name='profession',
            field=models.CharField(blank=True, max_length=150, verbose_name='Profession / Activité'),
        ),
        migrations.CreateModel(
            name='Guarantor',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Identifiant unique universel (UUIDv4)', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Dernière modification')),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text="Indique si l'enregistrement est actif ou archivé (soft delete)", verbose_name='Actif')),
                ('full_name', models.CharField(max_length=150, verbose_name='Nom et prénom du garant')),
                ('relationship', models.CharField(blank=True, max_length=100, verbose_name='Lien avec le locataire')),
                ('phone_number', models.CharField(max_length=30, verbose_name='Téléphone')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('id_card_number', models.CharField(blank=True, max_length=50, verbose_name="Numéro de pièce d'identité")),
                ('profession', models.CharField(blank=True, max_length=150, verbose_name='Profession')),
                ('monthly_income', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Revenus mensuels du garant')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='guarantors', to='tenants.tenant', verbose_name='Locataire')),
            ],
            options={
                'verbose_name': 'Garant / Caution Solidaire',
                'verbose_name_plural': 'Garants & Cautions Solidaires',
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
    ]
