# Generated by Django 5.1.15 on 2026-08-21 12:21

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('billing', '0001_initial'),
        ('tenants', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Identifiant unique universel (UUIDv4)', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Dernière modification')),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text="Indique si l'enregistrement est actif ou archivé (soft delete)", verbose_name='Actif')),
                ('payment_number', models.CharField(db_index=True, max_length=50, unique=True, verbose_name='Numéro de reçu / Référence paiement')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14, verbose_name='Montant total perçu (Decimal)')),
                ('payment_date', models.DateField(db_index=True, verbose_name="Date d'encaissement")),
                ('payment_method', models.CharField(choices=[('BANK_TRANSFER', 'Virement bancaire'), ('CASH', 'Espèces'), ('CHECK', 'Chèque'), ('CARD', 'Carte bancaire'), ('DIRECT_DEBIT', 'Prélèvement automatique'), ('OTHER', 'Autre')], default='BANK_TRANSFER', max_length=30, verbose_name='Mode de règlement')),
                ('reference_number', models.CharField(blank=True, max_length=100, verbose_name='Référence transaction / Chèque')),
                ('status', models.CharField(choices=[('COMPLETED', 'Validé / Encaissé'), ('PENDING', 'En attente de compensation'), ('CANCELLED', 'Annulé / Rejeté')], db_index=True, default='COMPLETED', max_length=20, verbose_name='Statut du paiement')),
                ('notes', models.TextField(blank=True, verbose_name='Remarques et annotations')),
                ('owner', models.ForeignKey(help_text='Propriétaire gestionnaire de cette ressource', on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_owned', to=settings.AUTH_USER_MODEL, verbose_name='Propriétaire')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='tenants.tenant', verbose_name='Locataire émetteur')),
            ],
            options={
                'verbose_name': 'Paiement',
                'verbose_name_plural': 'Paiements',
                'ordering': ['-payment_date'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PaymentAllocation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Identifiant unique universel (UUIDv4)', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Dernière modification')),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text="Indique si l'enregistrement est actif ou archivé (soft delete)", verbose_name='Actif')),
                ('allocated_amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Montant alloué')),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='allocations', to='billing.rentinvoice', verbose_name="Facture d'échéance imputée")),
                ('payment', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='allocations', to='payments.payment', verbose_name='Paiement source')),
            ],
            options={
                'verbose_name': 'Allocation de paiement',
                'verbose_name_plural': 'Allocations de paiement',
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
    ]
