# Generated by Django 5.1.15 on 2026-08-21 12:21

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('properties', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PropertyTax',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Identifiant unique universel (UUIDv4)', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Dernière modification')),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text="Indique si l'enregistrement est actif ou archivé (soft delete)", verbose_name='Actif')),
                ('tax_type', models.CharField(choices=[('PROPERTY_TAX', 'Taxe Foncière'), ('HOUSING_TAX', 'Taxe d’habitation'), ('INCOME_TAX', 'Impôt sur les revenus locatifs'), ('LOCAL_DEV', 'Taxe d’aménagement locale'), ('OTHER', 'Autre taxe')], default='PROPERTY_TAX', max_length=30, verbose_name="Type d'imposition")),
                ('fiscal_year', models.PositiveIntegerField(db_index=True, verbose_name='Année fiscale')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name="Montant de l'impôt (Decimal)")),
                ('due_date', models.DateField(verbose_name='Date limite de paiement')),
                ('paid_date', models.DateField(blank=True, null=True, verbose_name='Date effective de règlement')),
                ('is_paid', models.BooleanField(db_index=True, default=False, verbose_name='Réglé / Acquitté')),
                ('reference_notice', models.CharField(blank=True, max_length=100, verbose_name="Numéro d'avis d'imposition / Référence fiscale")),
                ('notice_file', models.FileField(blank=True, null=True, upload_to='taxes_notices/', verbose_name="Avis d'imposition (PDF/Scan)")),
                ('notes', models.TextField(blank=True, verbose_name='Notes')),
                ('owner', models.ForeignKey(help_text='Propriétaire gestionnaire de cette ressource', on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_owned', to=settings.AUTH_USER_MODEL, verbose_name='Propriétaire')),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='taxes', to='properties.property', verbose_name='Immeuble concerné')),
            ],
            options={
                'verbose_name': 'Impôt / Taxe foncière',
                'verbose_name_plural': 'Impôts & Taxes foncières',
                'ordering': ['-fiscal_year', '-due_date'],
                'abstract': False,
            },
        ),
    ]
