# Generated by Django 5.1.15 on 2026-08-21 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taxes', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='propertytax',
            options={'ordering': ['-fiscal_year', 'due_date'], 'verbose_name': 'Impôt / Taxe foncière', 'verbose_name_plural': 'Impôts & Taxes foncières'},
        ),
        migrations.AddField(
            model_name='propertytax',
            name='tax_number',
            field=models.CharField(blank=True, db_index=True, max_length=50, null=True, unique=True, verbose_name='Numéro fiscal de référence'),
        ),
        migrations.AlterField(
            model_name='propertytax',
            name='due_date',
            field=models.DateField(db_index=True, verbose_name='Date limite de paiement'),
        ),
        migrations.AlterField(
            model_name='propertytax',
            name='fiscal_year',
            field=models.PositiveIntegerField(db_index=True, verbose_name='Année / Exercice fiscal'),
        ),
        migrations.AlterField(
            model_name='propertytax',
            name='notes',
            field=models.TextField(blank=True, verbose_name='Notes et détails'),
        ),
        migrations.AlterField(
            model_name='propertytax',
            name='tax_type',
            field=models.CharField(choices=[('PROPERTY_TAX', 'Taxe Foncière'), ('HOUSING_TAX', 'Taxe d’habitation'), ('INCOME_TAX', 'Impôt sur les revenus locatifs'), ('LOCAL_DEV', 'Taxe d’aménagement locale'), ('OTHER', 'Autre taxe')], db_index=True, default='PROPERTY_TAX', max_length=30, verbose_name="Type d'imposition"),
        ),
    ]
